### ISSUE TITLE
MultiPage issues with TwainSave

### ISSUE THREAD

**Issue by ArekStrojec** [dynarithmic/twainsave#1]
Dear Dynarithmic Support Team,

I am writing to seek assistance regarding an issue I am experiencing with the TWAINsave software when using the command line interface. Specifically, the --multipage parameter does not seem to function as expected.

Here is the command I am using (windows system):
c:\Path\twainsave-opensource.exe --filename c:\Path\Out\MultiPageFile.pdf --filetype pdf --multipage --color 2 --resolution 300

My expectation is that this command would produce a single multi-page PDF file. However, instead, it generates separate PDF files for each scanned page (tmultiPage.pdf,tmultiPage1.pdf ...).

Could you please provide guidance on why the --multipage parameter is not working as intended? Is there a specific configuration or additional parameter that I need to use to achieve a multi-page PDF output?

I appreciate any assistance or suggestions you can offer to resolve this issue.

Thank you for your support.

Best regards,
Arek

**Comment by dynarithmic** [comment]
Please try the executables found in the [master staging](https://github.com/dynarithmic/twainsave/tree/master-staging/binaries) repository.

The issue is that the C++ wrapper was updated in the main DTWAIN repository, but not updated with the master repo for TwainSave.  

Note that the master repo for TwainSave has been dormant for almost a year now.  There still needs to be more testing before the master-staging repo will merge with master, so you should continue to use what's in master-repo at the present time.

**Comment by ArekStrojec** [comment]
I downloaded version 1.0.8

Problem has been solved

thank you for your support
